### ISSUE TITLE
Issue: Duplicate Loggers are initialized if multiple 'started' event is emitted 

### ISSUE THREAD

**Issue by slahiri** [yantrashala/loopback-component-logger#13] opened 2016-06-10 03:56 UTC
server/server.js has the following code `app.emit('started', baseUrl);` if emitted multiple times gives a duplicate Logger error.

The code in loopbackHook.js

``` javascript
     var enableAPI = config.enableAPI || false;
     if(enableAPI) {
         // adding log management api
         loggerModel.addModel(app);
         app.on('started', function(){
             loggerModel.attachLoggerMap(loggerMap);
         });
     }
```

`app.on` can be changed to `app.once` to prevent `loggerModel.addMode(app)` to be executed multiple times

**Comment by pbhadauria2000** [comment] 2016-06-10 06:16
Thanks Sid for resolving the issue. I think the issue is resolved and we can close this issue.

**Closed as completed by pbhadauria2000** 2016-06-10 06:16 UTC
